### ISSUE TITLE
Joining the OCA and contributing your modules to OCA/l10n-usa

### ISSUE THREAD

**Issue by max3903** [thinkwelltwd/countinghouse#1]
Hello @thinkwelltwd,

We have been using your modules at @ursais and I was wondering if you would be interested to give them more visibility and share the maintenance/migration cost with us at https://github.com/OCA/l10n-usa?

You would need to sign and send the CLA at https://odoo-community.org/page/cla. Would that be an issue?

Any questions or concerns, please let me know.

**Comment by thinkwelltwd** [comment]
Yes, I'd be interested in that. Currently in the process of upgrading our database from v10 to v12 so these modules are going to get updated in the next few weeks or so. 

I'm already an OCA member the CLA is taken care of.

**Comment by max3903** [comment]
Awesome. Thank you.

Regarding the modules migration, I quoted it to a customer today. Depending on their approval, we could be starting the migration next week. I will let you know here.

Have a great day!

**Comment by max3903** [comment]
@thinkwelltwd We got the approval to migrate:

* account_banking_ach_credit_transfer: https://github.com/OCA/l10n-usa/pull/38
* account_banking_ach_direct_debit: https://github.com/OCA/l10n-usa/pull/39
* account_banking_ach_base: https://github.com/OCA/l10n-usa/pull/40

@murtuzasaleh will be working on it.
